spring:
  application:
    name: cutting
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:Wiseman9527}
    url: ${MYSQL_URL:jdbc:mysql://10.1.6.156:3306/opt_omc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  ai:
    mcp:
      server:
        protocol: STATELESS
        name: streamable-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This streamable server provides real-time notifications"
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
        enabled: true
logging:
  level:
    org.hibernate.orm.jdbc. bind : TRACE

