-- +goose Up
-- +goose StatementBegin
INSERT INTO `role_permissions` (`role_code`, `permission_code`) VALUES
-- AI 相关权限 - 所有角色
('R_SUPER', 'ai:model:view'),
('R_SUPER', 'ai:chat:send'),
('R_SUPER', 'ai:prompt:view'),
('R_SUPER', 'ai:prompt:save'),
('R_SUPER', 'ai:prompt:switch'),
('R_SUPER', 'ai:prompt:delete'),
('R_SUPER', 'ai:prompt:reset'),
('R_SUPER', 'ai:vocabulary:view'),
('R_SUPER', 'ai:vocabulary:add'),
('R_SUPER', 'ai:vocabulary:edit'),
('R_SUPER', 'ai:vocabulary:delete'),
('R_SUPER', 'ai:note:view'),
('R_SUPER', 'ai:note:create'),
('R_SUPER', 'ai:note:edit'),
('R_SUPER', 'ai:note:delete'),
('R_SUPER', 'ai:history:view'),
('R_SUPER', 'ai:history:favorite'),
('R_SUPER', 'ai:history:edit'),
('R_SUPER', 'ai:history:delete'),
('R_SUPER', 'system:role:list'),
('R_SUPER', 'system:role:create'),
('R_SUPER', 'system:role:delete'),
('R_SUPER', 'system:role:permission:view'),
('R_SUPER', 'system:role:permission:update'),
('R_SUPER', 'system:ai-provider:view'),
('R_SUPER', 'system:ai-provider:create'),
('R_SUPER', 'system:ai-provider:update'),
('R_SUPER', 'system:ai-provider:delete'),
('R_SUPER', 'system:ai-model:view'),
('R_SUPER', 'system:ai-model:create'),
('R_SUPER', 'system:ai-model:update'),
('R_SUPER', 'system:ai-model:delete'),
-- R_ADMIN 权限
('R_ADMIN', 'ai:model:view'),
('R_ADMIN', 'ai:chat:send'),
('R_ADMIN', 'ai:prompt:view'),
('R_ADMIN', 'ai:prompt:save'),
('R_ADMIN', 'ai:prompt:switch'),
('R_ADMIN', 'ai:prompt:delete'),
('R_ADMIN', 'ai:prompt:reset'),
('R_ADMIN', 'ai:vocabulary:view'),
('R_ADMIN', 'ai:vocabulary:add'),
('R_ADMIN', 'ai:vocabulary:edit'),
('R_ADMIN', 'ai:vocabulary:delete'),
('R_ADMIN', 'ai:note:view'),
('R_ADMIN', 'ai:note:create'),
('R_ADMIN', 'ai:note:edit'),
('R_ADMIN', 'ai:note:delete'),
('R_ADMIN', 'ai:history:view'),
('R_ADMIN', 'ai:history:favorite'),
('R_ADMIN', 'ai:history:edit'),
('R_ADMIN', 'ai:history:delete'),
('R_ADMIN', 'system:role:list'),
('R_ADMIN', 'system:role:create'),
('R_ADMIN', 'system:role:delete'),
('R_ADMIN', 'system:role:permission:view'),
('R_ADMIN', 'system:role:permission:update'),
('R_ADMIN', 'system:ai-provider:view'),
('R_ADMIN', 'system:ai-provider:create'),
('R_ADMIN', 'system:ai-provider:update'),
('R_ADMIN', 'system:ai-provider:delete'),
('R_ADMIN', 'system:ai-model:view'),
('R_ADMIN', 'system:ai-model:create'),
('R_ADMIN', 'system:ai-model:update'),
('R_ADMIN', 'system:ai-model:delete'),
-- R_USER 权限（普通用户只有基础权限）
('R_USER', 'ai:model:view'),
('R_USER', 'ai:chat:send'),
('R_USER', 'ai:prompt:view'),
('R_USER', 'ai:prompt:save'),
('R_USER', 'ai:prompt:switch'),
('R_USER', 'ai:prompt:delete'),
('R_USER', 'ai:prompt:reset'),
('R_USER', 'ai:vocabulary:view'),
('R_USER', 'ai:vocabulary:add'),
('R_USER', 'ai:vocabulary:edit'),
('R_USER', 'ai:vocabulary:delete'),
('R_USER', 'ai:note:view'),
('R_USER', 'ai:note:create'),
('R_USER', 'ai:note:edit'),
('R_USER', 'ai:note:delete'),
('R_USER', 'ai:history:view'),
('R_USER', 'ai:history:favorite'),
('R_USER', 'ai:history:edit'),
('R_USER', 'ai:history:delete')
ON DUPLICATE KEY UPDATE `permission_code` = VALUES(`permission_code`);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM `role_permissions` WHERE `permission_code` IN (
  'ai:model:view', 'ai:chat:send',
  'ai:prompt:view', 'ai:prompt:save', 'ai:prompt:switch', 'ai:prompt:delete', 'ai:prompt:reset',
  'ai:vocabulary:view', 'ai:vocabulary:add', 'ai:vocabulary:edit', 'ai:vocabulary:delete',
  'ai:note:view', 'ai:note:create', 'ai:note:edit', 'ai:note:delete',
  'ai:history:view', 'ai:history:favorite', 'ai:history:edit', 'ai:history:delete',
  'system:role:list', 'system:role:create', 'system:role:delete',
  'system:role:permission:view', 'system:role:permission:update',
  'system:ai-provider:view', 'system:ai-provider:create', 'system:ai-provider:update', 'system:ai-provider:delete',
  'system:ai-model:view', 'system:ai-model:create', 'system:ai-model:update', 'system:ai-model:delete'
);
-- +goose StatementEnd
