/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  ai_chat: () => import("@/views/ai/chat/index.vue"),
  "ai_custom-training": () => import("@/views/ai/custom-training/[id].vue"),
  ai_decision: () => import("@/views/ai/decision/index.vue"),
  ai_emergency: () => import("@/views/ai/emergency/index.vue"),
  ai_exercise: () => import("@/views/ai/exercise/index.vue"),
  ai_history: () => import("@/views/ai/history/index.vue"),
  ai_memory: () => import("@/views/ai/memory/index.vue"),
  ai_note: () => import("@/views/ai/note/index.vue"),
  ai_social: () => import("@/views/ai/social/index.vue"),
  ai_training: () => import("@/views/ai/training/index.vue"),
  ai_vocabulary: () => import("@/views/ai/vocabulary/index.vue"),
  "cut_bar-detail": () => import("@/views/cut/bar-detail/[id].vue"),
  cut_bar: () => import("@/views/cut/bar/index.vue"),
  cut_history: () => import("@/views/cut/history/index.vue"),
  "cut_plane-detail": () => import("@/views/cut/plane-detail/[id].vue"),
  cut_plane: () => import("@/views/cut/plane/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "system_ai-config": () => import("@/views/system/ai-config/index.vue"),
  system_permission: () => import("@/views/system/permission/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
